
[mqtt]
serverAddress="tcp://localhost:1883"
baseTopic="mybaseTopic/monitoring"
user=""
password=""

[http]

[device_nodered]
watchTimeOut=2
watchTopics="home/agents/nodered/watchdog"

[agent_switchcontrol]
exec="sleep 100"
watchTopics="home/agents"
# watchTimeOut=

